// Turns a light-on-dark image into ASCII art for the dragon layer. Each
// generated file records the exact command(s) that produced it.
//
//   node scripts/ascii-art.mjs <image> [cols=64] [--crop=x,y,w,h] [--rotate=0|90|180|270]
//        [--flip] [--export=asciiDragon] [--bare] > components/ascii-dragon-art.ts
//
// The source illustration is scripts/dragon-source.png.
//
// Pixels are sampled in a headless Chromium canvas (Playwright is already a dev
// dependency), cropped to the subject's bounding box, and mapped to a density
// ramp: brighter pixel → denser glyph. Cells are sampled 0.6:1 (w:h) to match
// a monospace advance at line-height 1, so the art isn't stretched.
// --crop picks a region of the source (in its pixels) first; --rotate turns it
// clockwise before sampling; --flip mirrors it before the turn. --bare drops the
// header comment, for appending a second export to the same file.
import { readFileSync } from "node:fs";
import { extname } from "node:path";
import { chromium } from "@playwright/test";

const args = process.argv.slice(2);
const flags = Object.fromEntries(
  args.filter((a) => a.startsWith("--")).map((a) => {
    const [key, value] = a.slice(2).split("=");
    return [key, value ?? true];
  }),
);
const [imagePath, colsArg] = args.filter((a) => !a.startsWith("--"));
if (!imagePath) {
  console.error("usage: node scripts/ascii-art.mjs <image> [cols] [--crop=x,y,w,h] [--rotate=deg] [--flip] [--export=name]");
  process.exit(1);
}
const cols = Number(colsArg ?? 64);
const rotate = Number(flags.rotate ?? 0);
const flip = Boolean(flags.flip);
const crop = typeof flags.crop === "string" ? flags.crop.split(",").map(Number) : null;
const exportName = typeof flags.export === "string" ? flags.export : "asciiDragon";
const bare = Boolean(flags.bare);
const CHAR_ASPECT = 0.6;
const RAMP = " .,:;-=+*x#%@";
const THRESHOLD = 28; // luminance (0–255) below which a pixel counts as background

const mime = extname(imagePath) === ".jpg" ? "image/jpeg" : "image/png";
const dataUrl = `data:${mime};base64,${readFileSync(imagePath).toString("base64")}`;

const browser = await chromium.launch();
const page = await browser.newPage();
const lines = await page.evaluate(
  async ({ dataUrl, cols, crop, rotate, flip, CHAR_ASPECT, RAMP, THRESHOLD }) => {
    const img = new Image();
    img.src = dataUrl;
    await img.decode();
    const [cx, cy, cw, ch] = crop ?? [0, 0, img.width, img.height];
    const quarterTurn = Math.round(rotate / 90) % 2 !== 0;
    const canvas = document.createElement("canvas");
    canvas.width = quarterTurn ? ch : cw;
    canvas.height = quarterTurn ? cw : ch;
    const ctx = canvas.getContext("2d");
    ctx.translate(canvas.width / 2, canvas.height / 2);
    ctx.rotate((rotate * Math.PI) / 180);
    if (flip) ctx.scale(-1, 1);
    ctx.drawImage(img, cx, cy, cw, ch, -cw / 2, -ch / 2, cw, ch);
    const { data, width, height } = ctx.getImageData(0, 0, canvas.width, canvas.height);
    const lum = (x, y) => {
      const i = (y * width + x) * 4;
      return 0.2126 * data[i] + 0.7152 * data[i + 1] + 0.0722 * data[i + 2];
    };

    // Bounding box of the subject.
    let x0 = width, y0 = height, x1 = 0, y1 = 0;
    for (let y = 0; y < height; y++)
      for (let x = 0; x < width; x++)
        if (lum(x, y) > THRESHOLD) {
          x0 = Math.min(x0, x); y0 = Math.min(y0, y);
          x1 = Math.max(x1, x); y1 = Math.max(y1, y);
        }

    const cellW = (x1 - x0 + 1) / cols;
    const cellH = cellW / CHAR_ASPECT;
    const rows = Math.ceil((y1 - y0 + 1) / cellH);
    const out = [];
    for (let r = 0; r < rows; r++) {
      let line = "";
      for (let c = 0; c < cols; c++) {
        // Average the cell's luminance.
        let sum = 0, n = 0;
        for (let y = Math.floor(y0 + r * cellH); y < Math.min(y1 + 1, y0 + (r + 1) * cellH); y++)
          for (let x = Math.floor(x0 + c * cellW); x < Math.min(x1 + 1, x0 + (c + 1) * cellW); x++) {
            sum += lum(x, y);
            n++;
          }
        const v = n ? sum / n : 0;
        const t = Math.max(0, (v - THRESHOLD) / (255 - THRESHOLD));
        line += RAMP[Math.min(RAMP.length - 1, Math.round(Math.pow(t, 0.8) * (RAMP.length - 1)))];
      }
      out.push(line.trimEnd());
    }
    return out;
  },
  { dataUrl, cols, crop, rotate, flip, CHAR_ASPECT, RAMP, THRESHOLD },
);
await browser.close();

if (!bare) console.log("// Generated by scripts/ascii-art.mjs — don't edit by hand.");
console.log(`// node scripts/ascii-art.mjs ${process.argv.slice(2).join(" ")}`);
console.log(`export const ${exportName} = ${JSON.stringify(lines.join("\n"))};`);
